/* Zonico - schema Firebird 2.5
   Creazione database (isql):
     CREATE DATABASE 'C:\Zonico\ZONICO.FDB' USER 'SYSDBA' PASSWORD 'masterkey'
       PAGE_SIZE 8192 DEFAULT CHARACTER SET ISO8859_1;
   L'applicazione crea comunque gli oggetti mancanti al primo avvio. */

CREATE TABLE ZONE (
  ID INTEGER NOT NULL,
  CODICE VARCHAR(20) NOT NULL,
  DESCRIZIONE VARCHAR(200) NOT NULL,
  SUPERFICIE DOUBLE PRECISION DEFAULT 0,
  ATTIVA SMALLINT DEFAULT 1,
  CONSTRAINT PK_ZONE PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IDX_ZONE_CODICE ON ZONE (CODICE);

CREATE GENERATOR GEN_ZONE_ID;

CREATE TABLE UTENTI (
  ID INTEGER NOT NULL,
  NOME VARCHAR(120) NOT NULL,
  PIN VARCHAR(8) NOT NULL,
  CONSTRAINT PK_UTENTI PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IDX_UTENTI_PIN ON UTENTI (PIN);

CREATE GENERATOR GEN_UTENTI_ID;

INSERT INTO UTENTI (ID, NOME, PIN)
  VALUES (GEN_ID(GEN_UTENTI_ID, 1), 'Amministratore', '12345');

COMMIT;
