/* ============================================================
   ZONICO - Creazione completa del database
   Compatibile con Firebird 2.5 (e con le versioni successive)
   
   NOMENCLATURA CAMPI:
   Ogni campo TRANNE gli ID inizia con la prima lettera del nome della tabella:
   - RUOLI: ID / R_*
   - UTENTI: ID / U_*
   - CLIENTI: ID / C_*
   - ARTICOLI: ID / A_*
   - MOVIMENTI_MAGAZZINO: ID / M_*
   - ORDINI: ID / O_*
   - RIGHE_ORDINE: ID / RO_*
   - FATTURE: ID / F_*
   - SCADENZE: ID / S_*
   - NUMERATORI: N_*
   - AREE: AR_*
   - PERMESSI_AREA: PA_*

   COME ESEGUIRLO
   Con isql (incluso in Firebird), da riga di comando:

       isql -u SYSDBA -p masterkey
       SQL> CREATE DATABASE 'C:\Zonico\DB\ZONICO.FDB'
            USER 'SYSDBA' PASSWORD 'masterkey'
            PAGE_SIZE 8192 DEFAULT CHARACTER SET UTF8;
       SQL> INPUT 'C:\Users\user\Desktop\Zonico\db\zonico_schema.sql';
       SQL> QUIT;

   Con FlameRobin o IBExpert: creare prima un database vuoto
   (character set UTF8), aprirlo, poi eseguire questo file per intero.

   NOTA IMPORTANTE: lo script e' diviso in blocchi separati da COMMIT.
   ============================================================ */


/* ============================================================
   1. TABELLE
   ============================================================ */

CREATE TABLE RUOLI (
    ID              INTEGER NOT NULL,
    R_DESCRIZIONE   VARCHAR(50) NOT NULL,
    CONSTRAINT PK_RUOLI PRIMARY KEY (ID),
    CONSTRAINT UQ_RUOLI_DESCR UNIQUE (R_DESCRIZIONE)
);

CREATE TABLE UTENTI (
    ID              INTEGER NOT NULL,
    U_USERNAME      VARCHAR(50) NOT NULL,
    U_PASSWORD_HASH VARCHAR(128) NOT NULL,
    U_PIN           VARCHAR(10),
    U_ID_RUOLO      INTEGER NOT NULL,
    U_NOME_COMPLETO VARCHAR(100),
    U_ATTIVO        SMALLINT DEFAULT 1 NOT NULL,
    U_DATA_CREAZIONE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_UTENTI PRIMARY KEY (ID),
    CONSTRAINT UQ_UTENTI_USERNAME UNIQUE (U_USERNAME),
    CONSTRAINT FK_UTENTI_RUOLO FOREIGN KEY (U_ID_RUOLO) REFERENCES RUOLI (ID)
);

CREATE TABLE CLIENTI (
    ID              INTEGER NOT NULL,
    C_RAGIONE_SOCIALE VARCHAR(150) NOT NULL,
    C_PARTITA_IVA   VARCHAR(20),
    C_CODICE_FISCALE VARCHAR(20),
    C_INDIRIZZO     VARCHAR(150),
    C_CITTA         VARCHAR(80),
    C_CAP           VARCHAR(10),
    C_PROVINCIA     VARCHAR(4),
    C_TELEFONO      VARCHAR(30),
    C_EMAIL         VARCHAR(100),
    C_NOTE          BLOB SUB_TYPE TEXT,
    C_ATTIVO        SMALLINT DEFAULT 1 NOT NULL,
    C_DATA_CREAZIONE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CLIENTI PRIMARY KEY (ID)
);

CREATE TABLE ARTICOLI (
    ID              INTEGER NOT NULL,
    A_CODICE        VARCHAR(30) NOT NULL,
    A_DESCRIZIONE   VARCHAR(150) NOT NULL,
    A_UNITA_MISURA  VARCHAR(10) DEFAULT 'PZ',
    A_PREZZO_UNITARIO NUMERIC(15,2) DEFAULT 0 NOT NULL,
    A_GIACENZA      NUMERIC(15,3) DEFAULT 0 NOT NULL,
    A_GIACENZA_MINIMA NUMERIC(15,3) DEFAULT 0,
    A_ATTIVO        SMALLINT DEFAULT 1 NOT NULL,
    CONSTRAINT PK_ARTICOLI PRIMARY KEY (ID),
    CONSTRAINT UQ_ARTICOLI_CODICE UNIQUE (A_CODICE)
);

CREATE TABLE MOVIMENTI_MAGAZZINO (
    ID              INTEGER NOT NULL,
    M_ID_ARTICOLO   INTEGER NOT NULL,
    M_TIPO          CHAR(1) NOT NULL,
    M_QUANTITA      NUMERIC(15,3) NOT NULL,
    M_DATA_MOVIMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    M_CAUSALE       VARCHAR(100),
    M_ID_UTENTE     INTEGER,
    M_NOTE          VARCHAR(200),
    CONSTRAINT PK_MOVIMENTI PRIMARY KEY (ID),
    CONSTRAINT FK_MOVIMENTI_ARTICOLO FOREIGN KEY (M_ID_ARTICOLO) REFERENCES ARTICOLI (ID),
    CONSTRAINT FK_MOVIMENTI_UTENTE FOREIGN KEY (M_ID_UTENTE) REFERENCES UTENTI (ID),
    CONSTRAINT CK_MOVIMENTI_TIPO CHECK (M_TIPO IN ('C', 'S'))
);

CREATE TABLE ORDINI (
    ID              INTEGER NOT NULL,
    O_NUMERO_ORDINE VARCHAR(30) NOT NULL,
    O_ID_CLIENTE    INTEGER NOT NULL,
    O_DATA_ORDINE   DATE DEFAULT CURRENT_DATE NOT NULL,
    O_STATO         VARCHAR(20) DEFAULT 'Aperto' NOT NULL,
    O_TOTALE        NUMERIC(15,2) DEFAULT 0 NOT NULL,
    O_NOTE          BLOB SUB_TYPE TEXT,
    CONSTRAINT PK_ORDINI PRIMARY KEY (ID),
    CONSTRAINT UQ_ORDINI_NUMERO UNIQUE (O_NUMERO_ORDINE),
    CONSTRAINT FK_ORDINI_CLIENTE FOREIGN KEY (O_ID_CLIENTE) REFERENCES CLIENTI (ID)
);

CREATE TABLE RIGHE_ORDINE (
    ID              INTEGER NOT NULL,
    RO_ID_ORDINE    INTEGER NOT NULL,
    RO_ID_ARTICOLO  INTEGER NOT NULL,
    RO_QUANTITA     NUMERIC(15,3) NOT NULL,
    RO_PREZZO_UNITARIO NUMERIC(15,2) NOT NULL,
    RO_TOTALE_RIGA  NUMERIC(15,2) NOT NULL,
    CONSTRAINT PK_RIGHE_ORDINE PRIMARY KEY (ID),
    CONSTRAINT FK_RIGHE_ORDINE FOREIGN KEY (RO_ID_ORDINE) REFERENCES ORDINI (ID) ON DELETE CASCADE,
    CONSTRAINT FK_RIGHE_ARTICOLO FOREIGN KEY (RO_ID_ARTICOLO) REFERENCES ARTICOLI (ID)
);

CREATE TABLE FATTURE (
    ID              INTEGER NOT NULL,
    F_NUMERO_FATTURA VARCHAR(30) NOT NULL,
    F_ID_ORDINE     INTEGER,
    F_ID_CLIENTE    INTEGER NOT NULL,
    F_DATA_FATTURA  DATE DEFAULT CURRENT_DATE NOT NULL,
    F_TOTALE        NUMERIC(15,2) DEFAULT 0 NOT NULL,
    F_STATO_PAGAMENTO VARCHAR(20) DEFAULT 'Da Pagare' NOT NULL,
    CONSTRAINT PK_FATTURE PRIMARY KEY (ID),
    CONSTRAINT UQ_FATTURE_NUMERO UNIQUE (F_NUMERO_FATTURA),
    CONSTRAINT FK_FATTURE_ORDINE FOREIGN KEY (F_ID_ORDINE) REFERENCES ORDINI (ID),
    CONSTRAINT FK_FATTURE_CLIENTE FOREIGN KEY (F_ID_CLIENTE) REFERENCES CLIENTI (ID)
);

CREATE TABLE SCADENZE (
    ID              INTEGER NOT NULL,
    S_ID_FATTURA    INTEGER NOT NULL,
    S_DATA_SCADENZA DATE NOT NULL,
    S_IMPORTO       NUMERIC(15,2) NOT NULL,
    S_PAGATO        SMALLINT DEFAULT 0 NOT NULL,
    S_DATA_PAGAMENTO DATE,
    S_MODALITA_PAGAMENTO VARCHAR(30),
    CONSTRAINT PK_SCADENZE PRIMARY KEY (ID),
    CONSTRAINT FK_SCADENZE_FATTURA FOREIGN KEY (S_ID_FATTURA) REFERENCES FATTURE (ID) ON DELETE CASCADE
);

/* Numeratori documenti: contatore progressivo per tipo e anno.
   Viene incrementato in modo atomico (UPDATE ... RETURNING) */
CREATE TABLE NUMERATORI (
    N_TIPO_DOCUMENTO VARCHAR(10) NOT NULL,
    N_ANNO          SMALLINT NOT NULL,
    N_ULTIMO_NUMERO INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_NUMERATORI PRIMARY KEY (N_TIPO_DOCUMENTO, N_ANNO)
);

/* Aree applicative e permessi per ruolo */
CREATE TABLE AREE (
    AR_CODICE       VARCHAR(10) NOT NULL,
    AR_DESCRIZIONE  VARCHAR(60) NOT NULL,
    AR_ORDINE       SMALLINT DEFAULT 0 NOT NULL,
    CONSTRAINT PK_AREE PRIMARY KEY (AR_CODICE)
);

CREATE TABLE PERMESSI_AREA (
    PA_ID_RUOLO     INTEGER NOT NULL,
    PA_CODICE_AREA  VARCHAR(10) NOT NULL,
    CONSTRAINT PK_PERMESSI_AREA PRIMARY KEY (PA_ID_RUOLO, PA_CODICE_AREA),
    CONSTRAINT FK_PERMESSI_RUOLO FOREIGN KEY (PA_ID_RUOLO) REFERENCES RUOLI (ID) ON DELETE CASCADE,
    CONSTRAINT FK_PERMESSI_AREA FOREIGN KEY (PA_CODICE_AREA) REFERENCES AREE (AR_CODICE) ON DELETE CASCADE
);

COMMIT;


/* ============================================================
   2. GENERATORI
   ============================================================ */

CREATE GENERATOR GEN_RUOLI_ID;
CREATE GENERATOR GEN_UTENTI_ID;
CREATE GENERATOR GEN_CLIENTI_ID;
CREATE GENERATOR GEN_ARTICOLI_ID;
CREATE GENERATOR GEN_MOVIMENTI_ID;
CREATE GENERATOR GEN_ORDINI_ID;
CREATE GENERATOR GEN_RIGHE_ORDINE_ID;
CREATE GENERATOR GEN_FATTURE_ID;
CREATE GENERATOR GEN_SCADENZE_ID;

COMMIT;


/* ============================================================
   3. TRIGGER
   ============================================================ */

SET TERM ^ ;

CREATE TRIGGER TRG_RUOLI_BI FOR RUOLI
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_RUOLI_ID, 1);
END^

CREATE TRIGGER TRG_UTENTI_BI FOR UTENTI
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_UTENTI_ID, 1);
END^

CREATE TRIGGER TRG_CLIENTI_BI FOR CLIENTI
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CLIENTI_ID, 1);
END^

CREATE TRIGGER TRG_ARTICOLI_BI FOR ARTICOLI
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_ARTICOLI_ID, 1);
END^

CREATE TRIGGER TRG_MOVIMENTI_BI FOR MOVIMENTI_MAGAZZINO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_MOVIMENTI_ID, 1);
END^

CREATE TRIGGER TRG_ORDINI_BI FOR ORDINI
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_ORDINI_ID, 1);
END^

CREATE TRIGGER TRG_RIGHE_ORDINE_BI FOR RIGHE_ORDINE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_RIGHE_ORDINE_ID, 1);
END^

CREATE TRIGGER TRG_FATTURE_BI FOR FATTURE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_FATTURE_ID, 1);
END^

CREATE TRIGGER TRG_SCADENZE_BI FOR SCADENZE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_SCADENZE_ID, 1);
END^

/* Giacenza aggiornata automaticamente: carico somma, scarico sottrae */
CREATE TRIGGER TRG_MOVIMENTI_AI FOR MOVIMENTI_MAGAZZINO
ACTIVE AFTER INSERT POSITION 0
AS
BEGIN
  IF (NEW.M_TIPO = 'C') THEN
    UPDATE ARTICOLI SET A_GIACENZA = A_GIACENZA + NEW.M_QUANTITA
     WHERE ID = NEW.M_ID_ARTICOLO;
  ELSE
    UPDATE ARTICOLI SET A_GIACENZA = A_GIACENZA - NEW.M_QUANTITA
     WHERE ID = NEW.M_ID_ARTICOLO;
END^

SET TERM ; ^

COMMIT;


/* ============================================================
   4. DATI INIZIALI
   ============================================================ */

INSERT INTO RUOLI (R_DESCRIZIONE) VALUES ('Amministratore');
INSERT INTO RUOLI (R_DESCRIZIONE) VALUES ('Operatore');

/* Utente iniziale: username = admin, PIN = 12345 (minimo 5 cifre) */
INSERT INTO UTENTI (U_USERNAME, U_PASSWORD_HASH, U_PIN, U_ID_RUOLO, U_NOME_COMPLETO)
    SELECT 'admin',
           '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918',
           '12345',
           R.ID,
           'Amministratore'
      FROM RUOLI R
     WHERE R.R_DESCRIZIONE = 'Amministratore';

/* Le quattro aree dell'applicazione */
INSERT INTO AREE (AR_CODICE, AR_DESCRIZIONE, AR_ORDINE) VALUES ('ANAG', 'Anagrafiche e Magazzino', 1);
INSERT INTO AREE (AR_CODICE, AR_DESCRIZIONE, AR_ORDINE) VALUES ('VEND', 'Vendite e Contabilita', 2);
INSERT INTO AREE (AR_CODICE, AR_DESCRIZIONE, AR_ORDINE) VALUES ('REPO', 'Report', 3);
INSERT INTO AREE (AR_CODICE, AR_DESCRIZIONE, AR_ORDINE) VALUES ('AMMI', 'Amministrazione', 4);

/* Permessi iniziali: l'amministratore accede a tutto, l'operatore a tutto tranne l'area Amministrazione */
INSERT INTO PERMESSI_AREA (PA_ID_RUOLO, PA_CODICE_AREA)
    SELECT R.ID, A.AR_CODICE
      FROM RUOLI R, AREE A
     WHERE R.R_DESCRIZIONE = 'Amministratore';

INSERT INTO PERMESSI_AREA (PA_ID_RUOLO, PA_CODICE_AREA)
    SELECT R.ID, A.AR_CODICE
      FROM RUOLI R, AREE A
     WHERE R.R_DESCRIZIONE = 'Operatore'
       AND A.AR_CODICE <> 'AMMI';

COMMIT;


/* ============================================================
   5. VERIFICA (facoltativa)
   ============================================================ */

/*
SELECT COUNT(*) AS TABELLE FROM RDB$RELATIONS WHERE RDB$SYSTEM_FLAG = 0;
SELECT COUNT(*) AS GENERATORI FROM RDB$GENERATORS WHERE RDB$SYSTEM_FLAG = 0;
SELECT COUNT(*) AS TRIGGER FROM RDB$TRIGGERS WHERE RDB$SYSTEM_FLAG = 0;
SELECT COUNT(*) AS RUOLI FROM RUOLI;
SELECT COUNT(*) AS UTENTI FROM UTENTI;
SELECT COUNT(*) AS AREE FROM AREE;
SELECT COUNT(*) AS PERMESSI FROM PERMESSI_AREA;
*/