/* Zonico - Gestionale Parrucchieri
   Script creazione database Firebird 2.5
   Uso: isql -i create_db.sql  (dopo aver modificato il path in CREATE DATABASE) */

SET SQL DIALECT 3;
SET NAMES UTF8;

CREATE DATABASE 'localhost:C:\Zonico\ZONICO.FDB'
  USER 'SYSDBA' PASSWORD 'masterkey'
  PAGE_SIZE 8192 DEFAULT CHARACTER SET UTF8;

/* ================= UTENTI E PERMESSI ================= */

CREATE TABLE UTENTI (
  ID          INTEGER NOT NULL,
  USERNAME    VARCHAR(30) NOT NULL,
  PASSWORD    VARCHAR(30) NOT NULL,
  NOME        VARCHAR(60),
  ADMIN       SMALLINT DEFAULT 0 NOT NULL,
  ATTIVO      SMALLINT DEFAULT 1 NOT NULL,
  CONSTRAINT PK_UTENTI PRIMARY KEY (ID),
  CONSTRAINT UQ_UTENTI_USERNAME UNIQUE (USERNAME)
);

CREATE TABLE MODULI (
  CODICE      VARCHAR(20) NOT NULL,
  DESCRIZIONE VARCHAR(60) NOT NULL,
  CONSTRAINT PK_MODULI PRIMARY KEY (CODICE)
);

CREATE TABLE PERMESSI (
  ID_UTENTE   INTEGER NOT NULL,
  MODULO      VARCHAR(20) NOT NULL,
  LETTURA     SMALLINT DEFAULT 1 NOT NULL,
  SCRITTURA   SMALLINT DEFAULT 0 NOT NULL,
  CANCELLA    SMALLINT DEFAULT 0 NOT NULL,
  CONSTRAINT PK_PERMESSI PRIMARY KEY (ID_UTENTE, MODULO),
  CONSTRAINT FK_PERMESSI_UTENTE FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID) ON DELETE CASCADE,
  CONSTRAINT FK_PERMESSI_MODULO FOREIGN KEY (MODULO) REFERENCES MODULI(CODICE)
);

/* ================= ANAGRAFICHE ================= */

CREATE TABLE CLIENTI (
  ID            INTEGER NOT NULL,
  COGNOME       VARCHAR(50) NOT NULL,
  NOME          VARCHAR(50),
  SESSO         CHAR(1),
  DATA_NASCITA  DATE,
  TELEFONO      VARCHAR(20),
  CELLULARE     VARCHAR(20),
  EMAIL         VARCHAR(100),
  INDIRIZZO     VARCHAR(100),
  CAP           VARCHAR(10),
  CITTA         VARCHAR(60),
  PROVINCIA     VARCHAR(2),
  CODICE_FISCALE VARCHAR(16),
  CONSENSO_PRIVACY SMALLINT DEFAULT 0 NOT NULL,
  CONSENSO_MARKETING SMALLINT DEFAULT 0 NOT NULL,
  NOTE          BLOB SUB_TYPE TEXT,
  DATA_INSERIMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  ATTIVO        SMALLINT DEFAULT 1 NOT NULL,
  CONSTRAINT PK_CLIENTI PRIMARY KEY (ID)
);
CREATE INDEX IDX_CLIENTI_COGNOME ON CLIENTI (COGNOME, NOME);

CREATE TABLE OPERATORI (
  ID          INTEGER NOT NULL,
  NOME        VARCHAR(60) NOT NULL,
  TELEFONO    VARCHAR(20),
  COLORE      INTEGER DEFAULT 0 NOT NULL,
  ATTIVO      SMALLINT DEFAULT 1 NOT NULL,
  CONSTRAINT PK_OPERATORI PRIMARY KEY (ID)
);

CREATE TABLE SERVIZI (
  ID          INTEGER NOT NULL,
  DESCRIZIONE VARCHAR(80) NOT NULL,
  DURATA_MIN  INTEGER DEFAULT 30 NOT NULL,
  PREZZO      NUMERIC(10,2) DEFAULT 0 NOT NULL,
  ATTIVO      SMALLINT DEFAULT 1 NOT NULL,
  CONSTRAINT PK_SERVIZI PRIMARY KEY (ID)
);

CREATE TABLE PRODOTTI (
  ID          INTEGER NOT NULL,
  CODICE      VARCHAR(30),
  DESCRIZIONE VARCHAR(80) NOT NULL,
  PREZZO      NUMERIC(10,2) DEFAULT 0 NOT NULL,
  GIACENZA    INTEGER DEFAULT 0 NOT NULL,
  ATTIVO      SMALLINT DEFAULT 1 NOT NULL,
  CONSTRAINT PK_PRODOTTI PRIMARY KEY (ID)
);

CREATE TABLE PAGAMENTI (
  CODICE      VARCHAR(20) NOT NULL,
  DESCRIZIONE VARCHAR(60) NOT NULL,
  CONSTRAINT PK_PAGAMENTI PRIMARY KEY (CODICE)
);

/* ================= AGENDA ================= */

CREATE TABLE APPUNTAMENTI (
  ID            INTEGER NOT NULL,
  INIZIO        TIMESTAMP NOT NULL,
  FINE          TIMESTAMP NOT NULL,
  ID_CLIENTE    INTEGER,
  ID_OPERATORE  INTEGER,
  ID_SERVIZIO   INTEGER,
  STATO         VARCHAR(15) DEFAULT 'PRENOTATO' NOT NULL,
  NOTE          VARCHAR(255),
  CONSTRAINT PK_APPUNTAMENTI PRIMARY KEY (ID),
  CONSTRAINT FK_APP_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTI(ID),
  CONSTRAINT FK_APP_OPERATORE FOREIGN KEY (ID_OPERATORE) REFERENCES OPERATORI(ID),
  CONSTRAINT FK_APP_SERVIZIO FOREIGN KEY (ID_SERVIZIO) REFERENCES SERVIZI(ID),
  CONSTRAINT CK_APP_STATO CHECK (STATO IN ('PRENOTATO','CONFERMATO','ARRIVATO','COMPLETATO','ANNULLATO','NO_SHOW'))
);
CREATE INDEX IDX_APP_INIZIO ON APPUNTAMENTI (INIZIO, ID_OPERATORE);

/* ================= VENDITE ================= */

CREATE TABLE VENDITE (
  ID            INTEGER NOT NULL,
  DATA          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  ID_CLIENTE    INTEGER,
  ID_OPERATORE  INTEGER,
  ID_UTENTE     INTEGER,
  IMPONIBILE    NUMERIC(10,2) DEFAULT 0 NOT NULL,
  SCONTO        NUMERIC(10,2) DEFAULT 0 NOT NULL,
  TOTALE        NUMERIC(10,2) DEFAULT 0 NOT NULL,
  PAGAMENTO     VARCHAR(20),
  CHIUSA        SMALLINT DEFAULT 0 NOT NULL,
  NOTE          VARCHAR(255),
  CONSTRAINT PK_VENDITE PRIMARY KEY (ID),
  CONSTRAINT FK_VEN_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTI(ID),
  CONSTRAINT FK_VEN_OPERATORE FOREIGN KEY (ID_OPERATORE) REFERENCES OPERATORI(ID),
  CONSTRAINT FK_VEN_UTENTE FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI(ID),
  CONSTRAINT FK_VEN_PAGAMENTO FOREIGN KEY (PAGAMENTO) REFERENCES PAGAMENTI(CODICE)
);
CREATE INDEX IDX_VENDITE_DATA ON VENDITE (DATA);

CREATE TABLE VENDITE_RIGHE (
  ID            INTEGER NOT NULL,
  ID_VENDITA    INTEGER NOT NULL,
  TIPO          CHAR(1) DEFAULT 'S' NOT NULL,   /* S=servizio P=prodotto */
  ID_SERVIZIO   INTEGER,
  ID_PRODOTTO   INTEGER,
  DESCRIZIONE   VARCHAR(80) NOT NULL,
  QUANTITA      INTEGER DEFAULT 1 NOT NULL,
  PREZZO        NUMERIC(10,2) DEFAULT 0 NOT NULL,
  CONSTRAINT PK_VENDITE_RIGHE PRIMARY KEY (ID),
  CONSTRAINT FK_VR_VENDITA FOREIGN KEY (ID_VENDITA) REFERENCES VENDITE(ID) ON DELETE CASCADE,
  CONSTRAINT FK_VR_SERVIZIO FOREIGN KEY (ID_SERVIZIO) REFERENCES SERVIZI(ID),
  CONSTRAINT FK_VR_PRODOTTO FOREIGN KEY (ID_PRODOTTO) REFERENCES PRODOTTI(ID)
);

/* ================= GENERATORI E TRIGGER ================= */

CREATE GENERATOR GEN_UTENTI;
CREATE GENERATOR GEN_CLIENTI;
CREATE GENERATOR GEN_OPERATORI;
CREATE GENERATOR GEN_SERVIZI;
CREATE GENERATOR GEN_PRODOTTI;
CREATE GENERATOR GEN_APPUNTAMENTI;
CREATE GENERATOR GEN_VENDITE;
CREATE GENERATOR GEN_VENDITE_RIGHE;

SET TERM ^ ;

CREATE TRIGGER TR_UTENTI_BI FOR UTENTI ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_UTENTI, 1); END^

CREATE TRIGGER TR_CLIENTI_BI FOR CLIENTI ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_CLIENTI, 1); END^

CREATE TRIGGER TR_OPERATORI_BI FOR OPERATORI ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_OPERATORI, 1); END^

CREATE TRIGGER TR_SERVIZI_BI FOR SERVIZI ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_SERVIZI, 1); END^

CREATE TRIGGER TR_PRODOTTI_BI FOR PRODOTTI ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_PRODOTTI, 1); END^

CREATE TRIGGER TR_APPUNTAMENTI_BI FOR APPUNTAMENTI ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_APPUNTAMENTI, 1); END^

CREATE TRIGGER TR_VENDITE_BI FOR VENDITE ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_VENDITE, 1); END^

CREATE TRIGGER TR_VENDITE_RIGHE_BI FOR VENDITE_RIGHE ACTIVE BEFORE INSERT POSITION 0 AS
BEGIN IF (NEW.ID IS NULL) THEN NEW.ID = GEN_ID(GEN_VENDITE_RIGHE, 1); END^

/* Ricalcolo totale vendita quando cambiano le righe */
CREATE TRIGGER TR_VENDITE_RIGHE_AIUD FOR VENDITE_RIGHE ACTIVE AFTER INSERT OR UPDATE OR DELETE POSITION 0 AS
DECLARE VARIABLE VID INTEGER;
BEGIN
  IF (DELETING) THEN VID = OLD.ID_VENDITA; ELSE VID = NEW.ID_VENDITA;
  UPDATE VENDITE V SET
    V.IMPONIBILE = COALESCE((SELECT SUM(R.QUANTITA * R.PREZZO) FROM VENDITE_RIGHE R WHERE R.ID_VENDITA = :VID), 0),
    V.TOTALE = V.IMPONIBILE - V.SCONTO
  WHERE V.ID = :VID;
END^

SET TERM ; ^

/* ================= DATI INIZIALI ================= */

INSERT INTO MODULI VALUES ('CLIENTI',    'Anagrafica clienti');
INSERT INTO MODULI VALUES ('OPERATORI',  'Operatori');
INSERT INTO MODULI VALUES ('SERVIZI',    'Listino servizi');
INSERT INTO MODULI VALUES ('PRODOTTI',   'Prodotti');
INSERT INTO MODULI VALUES ('AGENDA',     'Agenda appuntamenti');
INSERT INTO MODULI VALUES ('VENDITE',    'Vendite / Cassa');
INSERT INTO MODULI VALUES ('REPORT',     'Report incassi');
INSERT INTO MODULI VALUES ('UTENTI',     'Gestione utenti e permessi');

INSERT INTO PAGAMENTI VALUES ('CONTANTI', 'Contanti');
INSERT INTO PAGAMENTI VALUES ('CARTA',    'Carta / Bancomat');
INSERT INTO PAGAMENTI VALUES ('BONIFICO', 'Bonifico');
INSERT INTO PAGAMENTI VALUES ('MISTO',    'Misto');

INSERT INTO UTENTI (USERNAME, PASSWORD, NOME, ADMIN) VALUES ('admin', 'admin', 'Amministratore', 1);

INSERT INTO SERVIZI (DESCRIZIONE, DURATA_MIN, PREZZO) VALUES ('Taglio donna', 45, 25);
INSERT INTO SERVIZI (DESCRIZIONE, DURATA_MIN, PREZZO) VALUES ('Taglio uomo', 30, 18);
INSERT INTO SERVIZI (DESCRIZIONE, DURATA_MIN, PREZZO) VALUES ('Piega', 30, 15);
INSERT INTO SERVIZI (DESCRIZIONE, DURATA_MIN, PREZZO) VALUES ('Colore', 90, 45);
INSERT INTO SERVIZI (DESCRIZIONE, DURATA_MIN, PREZZO) VALUES ('Shampoo', 15, 5);

COMMIT;
