object frmConferma: TfrmConferma
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  BorderStyle = bsDialog
  Caption = 'Conferma'
  ClientHeight = 170
  ClientWidth = 440
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Comfortaa'
  Font.Style = []
  FormStyle = fsNormal
  OldCreateOrder = False
  Position = poMainFormCenter
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 16
  object pnlMessaggio: TAdvPanel
    Left = 0
    Top = 0
    Width = 440
    Height = 110
    Align = alClient
    ParentColor = False
    TabOrder = 0
    Version = '2.4.0.0'
    BorderColor = clNone
    Caption.Text = ''
    Caption.Visible = False
    Fill.Color = clWhite
    Fill.ColorTo = clWhite
    Fill.BorderColor = clNone
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Comfortaa'
    Font.Style = []
    ParentFont = False
    object lblMessaggio: TLabel
      Left = 24
      Top = 28
      Width = 392
      Height = 60
      AutoSize = False
      Caption = 'Messaggio'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      WordWrap = True
    end
  end
  object pnlBottoni: TAdvPanel
    Left = 0
    Top = 110
    Width = 440
    Height = 60
    Align = alBottom
    ParentColor = False
    TabOrder = 1
    Version = '2.4.0.0'
    BorderColor = clNone
    Caption.Text = ''
    Caption.Visible = False
    Fill.Color = clWhite
    Fill.ColorTo = clWhite
    Fill.BorderColor = clSilver
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Comfortaa'
    Font.Style = []
    ParentFont = False
    object btnSi: TAdvGlowButton
      Left = 208
      Top = 14
      Width = 100
      Height = 32
      Caption = 'Si'
      Default = True
      ModalResult = 6
      TabOrder = 0
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      Version = '1.7.0.0'
    end
    object btnNo: TAdvGlowButton
      Left = 320
      Top = 14
      Width = 100
      Height = 32
      Cancel = True
      Caption = 'No'
      ModalResult = 7
      TabOrder = 1
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      Version = '1.7.0.0'
    end
  end
  object styConferma: TAdvFormStyler
    Style = tsWindows8
    Left = 32
    Top = 120
  end
end
