object frmConferma: TfrmConferma
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  BorderStyle = bsDialog
  Caption = 'Conferma'
  ClientHeight = 170
  ClientWidth = 440
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = 7893602
  Font.Height = -13
  Font.Name = 'Comfortaa'
  Font.Style = []
  FormStyle = fsNormal
  KeyPreview = True
  OldCreateOrder = False
  Position = poMainFormCenter
  OnCreate = FormCreate
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 16
  object pnlMessaggio: TPanel
    Left = 0
    Top = 0
    Width = 440
    Height = 110
    Align = alClient
    BevelOuter = bvNone
    Color = clWhite
    ParentBackground = False
    ParentColor = False
    TabOrder = 0
    object lblMessaggio: TLabel
      Left = 24
      Top = 28
      Width = 392
      Height = 60
      AutoSize = False
      Caption = 'Messaggio'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 7893602
      Font.Height = -13
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      WordWrap = True
    end
  end
  object pnlBottoni: TPanel
    Left = 0
    Top = 110
    Width = 440
    Height = 60
    Align = alBottom
    BevelOuter = bvNone
    Color = 15789804
    ParentBackground = False
    ParentColor = False
    TabOrder = 1
  end
end
