object frmBase: TfrmBase
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  BorderStyle = bsDialog
  Caption = 'Zonico'
  ClientHeight = 460
  ClientWidth = 640
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = 7893602
  Font.Height = -13
  Font.Name = 'Comfortaa'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poMainFormCenter
  OnCreate = FormCreate
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 16
  object pnlTestata: TPanel
    Left = 0
    Top = 0
    Width = 640
    Height = 72
    Align = alTop
    BevelOuter = bvNone
    Color = 15245660
    ParentBackground = False
    ParentColor = False
    TabOrder = 0
    object lblTitolo: TLabel
      Left = 24
      Top = 14
      Width = 400
      Height = 26
      AutoSize = False
      Caption = 'Titolo'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -21
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      Transparent = True
    end
    object lblDescrizione: TLabel
      Left = 26
      Top = 44
      Width = 560
      Height = 18
      AutoSize = False
      Caption = ''
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -12
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      Transparent = True
    end
  end
  object pnlCorpo: TPanel
    Left = 0
    Top = 72
    Width = 640
    Height = 320
    Align = alClient
    BevelOuter = bvNone
    Color = clWhite
    ParentBackground = False
    ParentColor = False
    TabOrder = 1
  end
  object pnlComandi: TPanel
    Left = 0
    Top = 392
    Width = 640
    Height = 68
    Align = alBottom
    BevelOuter = bvNone
    Color = 15789804
    ParentBackground = False
    ParentColor = False
    TabOrder = 2
  end
end
