object frmLogin: TfrmLogin
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  BorderStyle = bsDialog
  Caption = 'Zonico - Accesso'
  ClientHeight = 520
  ClientWidth = 720
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = 7893602
  Font.Height = -13
  Font.Name = 'Comfortaa'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poScreenCenter
  OnCreate = FormCreate
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 16
  object pnlBrand: TAdvPanel
    Left = 0
    Top = 0
    Width = 280
    Height = 520
    Align = alLeft
    ParentColor = False
    TabOrder = 0
    Version = '2.4.0.0'
    BorderColor = clNone
    Caption.Text = ''
    Caption.Visible = False
    Fill.Color = 15245660
    Fill.ColorTo = 15245660
    Fill.BorderColor = clNone
    Fill.ShadowColor = clNone
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Comfortaa'
    Font.Style = []
    ParentFont = False
    object imgLogo: TImage
      Left = 60
      Top = 120
      Width = 160
      Height = 160
      Center = True
      Proportional = True
      Stretch = True
      Transparent = True
    end
    object lblTitolo: TLabel
      Left = 0
      Top = 300
      Width = 280
      Height = 34
      Alignment = taCenter
      AutoSize = False
      Caption = 'Zonico'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -27
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      Transparent = True
    end
    object lblSottotitolo: TLabel
      Left = 0
      Top = 340
      Width = 280
      Height = 20
      Alignment = taCenter
      AutoSize = False
      Caption = 'Gestione aziendale'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      Transparent = True
    end
  end
  object pnlAccesso: TAdvPanel
    Left = 280
    Top = 0
    Width = 440
    Height = 520
    Align = alClient
    ParentColor = False
    TabOrder = 1
    Version = '2.4.0.0'
    BorderColor = clNone
    Caption.Text = ''
    Caption.Visible = False
    Fill.Color = clWhite
    Fill.ColorTo = clWhite
    Fill.BorderColor = clNone
    Fill.ShadowColor = clNone
    Font.Charset = DEFAULT_CHARSET
    Font.Color = 7893602
    Font.Height = -13
    Font.Name = 'Comfortaa'
    Font.Style = []
    ParentFont = False
    object lblPin: TLabel
      Left = 60
      Top = 40
      Width = 24
      Height = 16
      Caption = 'PIN'
    end
    object lblRegola: TLabel
      Left = 60
      Top = 108
      Width = 320
      Height = 16
      AutoSize = False
      Caption = 'PIN numerico da 5 a 8 cifre'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 14209740
      Font.Height = -12
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
    end
    object edtPin: TAdvEdit
      Left = 60
      Top = 62
      Width = 320
      Height = 38
      EditType = etString
      EmptyTextStyle = []
      MaxLength = 8
      PasswordChar = '#'
      ReadOnly = True
      Alignment = taCenter
      BorderStyle = bsSingle
      Color = clWhite
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 7893602
      Font.Height = -19
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      Version = '3.5.0.0'
      Visible = True
      EmptyText = 'Inserisci il PIN'
    end
    object pnlTastierino: TAdvPanel
      Left = 60
      Top = 136
      Width = 320
      Height = 316
      ParentColor = False
      TabOrder = 1
      Version = '2.4.0.0'
      BorderColor = clNone
      Caption.Text = ''
      Caption.Visible = False
      Fill.Color = clWhite
      Fill.ColorTo = clWhite
      Fill.BorderColor = clNone
      Fill.ShadowColor = clNone
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 7893602
      Font.Height = -13
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
    end
    object btnEsci: TAdvGlowButton
      Left = 280
      Top = 466
      Width = 100
      Height = 34
      Cancel = True
      Caption = 'Esci'
      ModalResult = 2
      TabOrder = 2
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 7893602
      Font.Height = -13
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      Version = '1.7.0.0'
    end
  end
  object styLogin: TAdvFormStyler
    Style = tsWindows8
    Left = 640
    Top = 468
  end
end
