object frmLogin: TfrmLogin
  Left = 0
  Top = 0
  BorderStyle = bsDialog
  Caption = 'Zonico - Accesso'
  ClientHeight = 220
  ClientWidth = 360
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  Position = poScreenCenter
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 15
  object pnlMain: TAdvPanel
    Left = 0
    Top = 0
    Width = 360
    Height = 220
    Align = alClient
    UseDockManager = True
    Version = '2.8.0.0'
    Caption.Visible = False
    Color = clWhite
    object lblTitolo: TLabel
      Left = 24
      Top = 16
      Width = 312
      Height = 32
      Alignment = taCenter
      AutoSize = False
      Caption = 'ZONICO'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 4227072
      Font.Height = -24
      Font.Name = 'Segoe UI'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object lblUser: TLabel
      Left = 24
      Top = 68
      Width = 40
      Height = 15
      Caption = 'Utente'
    end
    object lblPass: TLabel
      Left = 24
      Top = 112
      Width = 51
      Height = 15
      Caption = 'Password'
    end
    object edUser: TAdvEdit
      Left = 104
      Top = 64
      Width = 232
      Height = 23
      EmptyText = 'nome utente'
      LabelFont.Charset = DEFAULT_CHARSET
      LabelFont.Color = clWindowText
      LabelFont.Height = -11
      LabelFont.Name = 'Tahoma'
      LabelFont.Style = []
      Lookup.Font.Charset = DEFAULT_CHARSET
      Lookup.Font.Color = clWindowText
      Lookup.Font.Height = -11
      Lookup.Font.Name = 'Arial'
      Lookup.Font.Style = []
      Color = clWindow
      TabOrder = 0
      Text = ''
      Visible = True
      Version = '1.9.1.0'
    end
    object edPass: TAdvEdit
      Left = 104
      Top = 108
      Width = 232
      Height = 23
      EmptyText = 'password'
      LabelFont.Charset = DEFAULT_CHARSET
      LabelFont.Color = clWindowText
      LabelFont.Height = -11
      LabelFont.Name = 'Tahoma'
      LabelFont.Style = []
      Lookup.Font.Charset = DEFAULT_CHARSET
      Lookup.Font.Color = clWindowText
      Lookup.Font.Height = -11
      Lookup.Font.Name = 'Arial'
      Lookup.Font.Style = []
      Color = clWindow
      PasswordChar = '*'
      TabOrder = 1
      Text = ''
      Visible = True
      Version = '1.9.1.0'
    end
    object btnLogin: TAdvGlowButton
      Left = 136
      Top = 160
      Width = 96
      Height = 36
      Caption = 'Accedi'
      Default = True
      NotesFont.Charset = DEFAULT_CHARSET
      NotesFont.Color = clWindowText
      NotesFont.Height = -11
      NotesFont.Name = 'Tahoma'
      NotesFont.Style = []
      TabOrder = 2
      OnClick = btnLoginClick
      Appearance.ColorChecked = 16111818
      Appearance.ColorCheckedTo = 16367008
      Appearance.ColorDisabled = 15921906
      Appearance.ColorDisabledTo = 15921906
      Appearance.ColorDown = 16111818
      Appearance.ColorDownTo = 16367008
      Appearance.ColorHot = 16117985
      Appearance.ColorHotTo = 16372402
      Appearance.ColorMirror = 16111818
      Appearance.ColorMirrorTo = 16367008
      Appearance.ColorMirrorHot = 16117985
      Appearance.ColorMirrorHotTo = 16372402
      Appearance.ColorMirrorDown = 16111818
      Appearance.ColorMirrorDownTo = 16367008
      Appearance.ColorMirrorChecked = 16111818
      Appearance.ColorMirrorCheckedTo = 16367008
      Appearance.ColorMirrorDisabled = 15921906
      Appearance.ColorMirrorDisabledTo = 15921906
    end
    object btnEsci: TAdvGlowButton
      Left = 240
      Top = 160
      Width = 96
      Height = 36
      Caption = 'Esci'
      Cancel = True
      NotesFont.Charset = DEFAULT_CHARSET
      NotesFont.Color = clWindowText
      NotesFont.Height = -11
      NotesFont.Name = 'Tahoma'
      NotesFont.Style = []
      TabOrder = 3
      OnClick = btnEsciClick
      Appearance.ColorChecked = 16111818
      Appearance.ColorCheckedTo = 16367008
      Appearance.ColorDisabled = 15921906
      Appearance.ColorDisabledTo = 15921906
      Appearance.ColorDown = 16111818
      Appearance.ColorDownTo = 16367008
      Appearance.ColorHot = 16117985
      Appearance.ColorHotTo = 16372402
      Appearance.ColorMirror = 16111818
      Appearance.ColorMirrorTo = 16367008
      Appearance.ColorMirrorHot = 16117985
      Appearance.ColorMirrorHotTo = 16372402
      Appearance.ColorMirrorDown = 16111818
      Appearance.ColorMirrorDownTo = 16367008
      Appearance.ColorMirrorChecked = 16111818
      Appearance.ColorMirrorCheckedTo = 16367008
      Appearance.ColorMirrorDisabled = 15921906
      Appearance.ColorMirrorDisabledTo = 15921906
    end
  end
end
