object frmMain: TfrmMain
  Left = 0
  Top = 0
  Caption = 'Zonico'
  ClientHeight = 560
  ClientWidth = 900
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = 7893602
  Font.Height = -13
  Font.Name = 'Comfortaa'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 16
  object pnlTop: TPanel
    Left = 0
    Top = 0
    Width = 900
    Height = 96
    Align = alTop
    BevelOuter = bvNone
    Color = 15245660
    ParentBackground = False
    ParentColor = False
    TabOrder = 0
    object lblTitolo: TLabel
      Left = 32
      Top = 20
      Width = 120
      Height = 34
      Caption = 'Zonico'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -27
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      Transparent = True
    end
    object lblSottotitolo: TLabel
      Left = 34
      Top = 60
      Width = 400
      Height = 20
      AutoSize = False
      Caption = 'Utente'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      Transparent = True
    end
  end
  object pnlAree: TPanel
    Left = 0
    Top = 96
    Width = 900
    Height = 445
    Align = alClient
    BevelOuter = bvNone
    Color = clWhite
    ParentBackground = False
    ParentColor = False
    TabOrder = 1
  end
  object stbStato: TStatusBar
    Left = 0
    Top = 541
    Width = 900
    Height = 19
    Panels = <>
    SimplePanel = True
  end
end
