object frmMain: TfrmMain
  Left = 0
  Top = 0
  Caption = 'Zonico'
  ClientHeight = 520
  ClientWidth = 880
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Comfortaa'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 16
  object pnlTop: TAdvPanel
    Left = 0
    Top = 0
    Width = 880
    Height = 88
    Align = alTop
    UseDockManager = True
    ParentColor = False
    TabOrder = 0
    Version = '2.4.0.0'
    BorderColor = clNone
    Caption.Font.Charset = DEFAULT_CHARSET
    Caption.Font.Color = clWindowText
    Caption.Font.Height = -13
    Caption.Font.Name = 'Comfortaa'
    Caption.Font.Style = []
    Caption.Text = ''
    Caption.Visible = False
    Fill.Color = clWhite
    Fill.ColorTo = 15527152
    Fill.BorderColor = 14209752
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Comfortaa'
    Font.Style = []
    ParentFont = False
    object lblTitolo: TLabel
      Left = 24
      Top = 18
      Width = 66
      Height = 24
      Caption = 'Zonico'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = 13205820
      Font.Height = -19
      Font.Name = 'Comfortaa'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object lblSottotitolo: TLabel
      Left = 24
      Top = 50
      Width = 4
      Height = 16
      Caption = ''
    end
    object btnEsci: TAdvGlowButton
      Left = 750
      Top = 28
      Width = 110
      Height = 32
      Caption = 'Esci'
      NotesFont.Charset = DEFAULT_CHARSET
      NotesFont.Color = clWindowText
      NotesFont.Height = -11
      NotesFont.Name = 'Comfortaa'
      NotesFont.Style = []
      TabOrder = 0
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      Version = '1.7.0.0'
      OnClick = btnEsciClick
    end
  end
  object pnlAree: TAdvPanel
    Left = 0
    Top = 88
    Width = 880
    Height = 413
    Align = alClient
    UseDockManager = True
    ParentColor = False
    TabOrder = 1
    Version = '2.4.0.0'
    BorderColor = clNone
    Caption.Font.Charset = DEFAULT_CHARSET
    Caption.Font.Color = clWindowText
    Caption.Font.Height = -13
    Caption.Font.Name = 'Comfortaa'
    Caption.Font.Style = []
    Caption.Text = ''
    Caption.Visible = False
    Fill.Color = clWhite
    Fill.ColorTo = clWhite
    Fill.BorderColor = clNone
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Comfortaa'
    Font.Style = []
    ParentFont = False
    object btnAreaAnag: TAdvGlowButton
      Left = 90
      Top = 60
      Width = 320
      Height = 120
      Caption = 'Anagrafiche e Magazzino'
      NotesFont.Charset = DEFAULT_CHARSET
      NotesFont.Color = clWindowText
      NotesFont.Height = -11
      NotesFont.Name = 'Comfortaa'
      NotesFont.Style = []
      TabOrder = 0
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      Version = '1.7.0.0'
      OnClick = AreaClick
    end
    object btnAreaVend: TAdvGlowButton
      Left = 460
      Top = 60
      Width = 320
      Height = 120
      Caption = 'Vendite e Contabilita'
      NotesFont.Charset = DEFAULT_CHARSET
      NotesFont.Color = clWindowText
      NotesFont.Height = -11
      NotesFont.Name = 'Comfortaa'
      NotesFont.Style = []
      TabOrder = 1
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      Version = '1.7.0.0'
      OnClick = AreaClick
    end
    object btnAreaRepo: TAdvGlowButton
      Left = 90
      Top = 210
      Width = 320
      Height = 120
      Caption = 'Report'
      NotesFont.Charset = DEFAULT_CHARSET
      NotesFont.Color = clWindowText
      NotesFont.Height = -11
      NotesFont.Name = 'Comfortaa'
      NotesFont.Style = []
      TabOrder = 2
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      Version = '1.7.0.0'
      OnClick = AreaClick
    end
    object btnAreaAmmi: TAdvGlowButton
      Left = 460
      Top = 210
      Width = 320
      Height = 120
      Caption = 'Amministrazione'
      NotesFont.Charset = DEFAULT_CHARSET
      NotesFont.Color = clWindowText
      NotesFont.Height = -11
      NotesFont.Name = 'Comfortaa'
      NotesFont.Style = []
      TabOrder = 3
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -15
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      Version = '1.7.0.0'
      OnClick = AreaClick
    end
  end
  object stbStato: TStatusBar
    Left = 0
    Top = 501
    Width = 880
    Height = 19
    Panels = <>
    SimplePanel = True
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Comfortaa'
    Font.Style = []
    UseSystemFont = False
  end
  object styMain: TAdvFormStyler
    Style = tsWindows8
    Left = 424
    Top = 400
  end
end
