object frmReport: TfrmReport
  Left = 0
  Top = 0
  Caption = 'Report incassi'
  ClientHeight = 560
  ClientWidth = 900
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  FormStyle = fsMDIChild
  Visible = True
  WindowState = wsMaximized
  OnClose = FormClose
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 15
  object ToolBar: TAdvToolBar
    Left = 0
    Top = 0
    Width = 900
    Height = 40
    Align = alTop
    AutoSize = False
    ShowOptionIndicator = False
    ShowRightHandle = False
    Caption = 'ToolBar'
    Version = '7.4.0.0'
    object lblDal: TLabel
      Left = 8
      Top = 12
      Width = 20
      Height = 15
      Caption = 'Dal'
    end
    object dtDal: TAdvDateTimePicker
      Left = 36
      Top = 8
      Width = 120
      Height = 23
      Date = 45000.000000000000000000
      Format = 'dd/MM/yyyy'
      Time = 0.000000000000000000
      DateTime = 45000.000000000000000000
      TabOrder = 0
      Version = '1.6.4.0'
      Kind = dkDate
      LabelFont.Charset = DEFAULT_CHARSET
      LabelFont.Color = clWindowText
      LabelFont.Height = -11
      LabelFont.Name = 'Tahoma'
      LabelFont.Style = []
    end
    object lblAl: TLabel
      Left = 168
      Top = 12
      Width = 12
      Height = 15
      Caption = 'al'
    end
    object dtAl: TAdvDateTimePicker
      Left = 188
      Top = 8
      Width = 120
      Height = 23
      Date = 45000.000000000000000000
      Format = 'dd/MM/yyyy'
      Time = 0.000000000000000000
      DateTime = 45000.000000000000000000
      TabOrder = 1
      Version = '1.6.4.0'
      Kind = dkDate
      LabelFont.Charset = DEFAULT_CHARSET
      LabelFont.Color = clWindowText
      LabelFont.Height = -11
      LabelFont.Name = 'Tahoma'
      LabelFont.Style = []
    end
    object btnEsegui: TAdvToolBarButton
      Left = 320
      Top = 2
      Width = 80
      Height = 34
      Caption = 'Esegui'
      ShowCaption = True
      ShortCut = 116
      OnClick = btnEseguiClick
    end
    object btnMese: TAdvToolBarButton
      Left = 400
      Top = 2
      Width = 110
      Height = 34
      Caption = 'Mese corrente'
      ShowCaption = True
      OnClick = btnMeseClick
    end
    object btnStampa: TAdvToolBarButton
      Left = 510
      Top = 2
      Width = 80
      Height = 34
      Caption = 'Stampa'
      ShowCaption = True
      ShortCut = 16464
      OnClick = btnStampaClick
    end
  end
  object Pager: TAdvOfficePager
    Left = 0
    Top = 40
    Width = 900
    Height = 496
    Align = alClient
    ActivePage = pgGiorno
    AdvOfficePagerStyler = nil
    TabOrder = 1
    Version = '3.4.0.0'
    object pgGiorno: TAdvOfficePage
      Left = 1
      Top = 26
      Width = 898
      Height = 419
      Caption = 'Per giorno'
      object GridGiorno: TDBAdvGrid
        Left = 0
        Top = 0
        Width = 898
        Height = 419
        Align = alClient
        ColCount = 5
        FixedCols = 0
        RowCount = 2
        Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRangeSelect, goRowSelect]
        ScrollBars = ssBoth
        TabOrder = 0
        GridLineColor = 15790320
        GridFixedLineColor = 13421772
        ActiveCellFont.Charset = DEFAULT_CHARSET
        ActiveCellFont.Color = clWindowText
        ActiveCellFont.Height = -12
        ActiveCellFont.Name = 'Segoe UI'
        ActiveCellFont.Style = [fsBold]
        ControlLook.DropDownHeader.Font.Charset = DEFAULT_CHARSET
        ControlLook.DropDownHeader.Font.Color = clWindowText
        ControlLook.DropDownHeader.Font.Height = -11
        ControlLook.DropDownHeader.Font.Name = 'Tahoma'
        ControlLook.DropDownHeader.Font.Style = []
        ControlLook.DropDownHeader.Buttons = <>
        ControlLook.DropDownFooter.Font.Charset = DEFAULT_CHARSET
        ControlLook.DropDownFooter.Font.Color = clWindowText
        ControlLook.DropDownFooter.Font.Height = -11
        ControlLook.DropDownFooter.Font.Name = 'Tahoma'
        ControlLook.DropDownFooter.Font.Style = []
        ControlLook.DropDownFooter.Buttons = <>
        Filter = <>
        FilterDropDown.Font.Charset = DEFAULT_CHARSET
        FilterDropDown.Font.Color = clWindowText
        FilterDropDown.Font.Height = -11
        FilterDropDown.Font.Name = 'Tahoma'
        FilterDropDown.Font.Style = []
        FixedRowHeight = 26
        FixedFont.Charset = DEFAULT_CHARSET
        FixedFont.Color = clWindowText
        FixedFont.Height = -12
        FixedFont.Name = 'Segoe UI'
        FixedFont.Style = [fsBold]
        FloatFormat = '%.2f'
        Look = glOffice2019White
        PrintSettings.Font.Charset = DEFAULT_CHARSET
        PrintSettings.Font.Color = clWindowText
        PrintSettings.Font.Height = -11
        PrintSettings.Font.Name = 'Tahoma'
        PrintSettings.Font.Style = []
        PrintSettings.FixedFont.Charset = DEFAULT_CHARSET
        PrintSettings.FixedFont.Color = clWindowText
        PrintSettings.FixedFont.Height = -11
        PrintSettings.FixedFont.Name = 'Tahoma'
        PrintSettings.FixedFont.Style = []
        PrintSettings.HeaderFont.Charset = DEFAULT_CHARSET
        PrintSettings.HeaderFont.Color = clWindowText
        PrintSettings.HeaderFont.Height = -11
        PrintSettings.HeaderFont.Name = 'Tahoma'
        PrintSettings.HeaderFont.Style = []
        PrintSettings.FooterFont.Charset = DEFAULT_CHARSET
        PrintSettings.FooterFont.Color = clWindowText
        PrintSettings.FooterFont.Height = -11
        PrintSettings.FooterFont.Name = 'Tahoma'
        PrintSettings.FooterFont.Style = []
        SearchFooter.Font.Charset = DEFAULT_CHARSET
        SearchFooter.Font.Color = clWindowText
        SearchFooter.Font.Height = -11
        SearchFooter.Font.Name = 'Tahoma'
        SearchFooter.Font.Style = []
        ShowDesignHelper = False
        Version = '2.6.0.0'
        AutoCreateColumns = True
        AutoRemoveColumns = True
        Columns = <>
        DataSetType = dtNonSequenced
        DataSource = DSGiorno
        ShowUnicode = True
        PageMode = False
      end
    end
    object pgOperatore: TAdvOfficePage
      Left = 1
      Top = 26
      Width = 898
      Height = 419
      Caption = 'Per operatore'
      object GridOperatore: TDBAdvGrid
        Left = 0
        Top = 0
        Width = 898
        Height = 419
        Align = alClient
        ColCount = 5
        FixedCols = 0
        RowCount = 2
        Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRangeSelect, goRowSelect]
        ScrollBars = ssBoth
        TabOrder = 0
        GridLineColor = 15790320
        GridFixedLineColor = 13421772
        ActiveCellFont.Charset = DEFAULT_CHARSET
        ActiveCellFont.Color = clWindowText
        ActiveCellFont.Height = -12
        ActiveCellFont.Name = 'Segoe UI'
        ActiveCellFont.Style = [fsBold]
        ControlLook.DropDownHeader.Font.Charset = DEFAULT_CHARSET
        ControlLook.DropDownHeader.Font.Color = clWindowText
        ControlLook.DropDownHeader.Font.Height = -11
        ControlLook.DropDownHeader.Font.Name = 'Tahoma'
        ControlLook.DropDownHeader.Font.Style = []
        ControlLook.DropDownHeader.Buttons = <>
        ControlLook.DropDownFooter.Font.Charset = DEFAULT_CHARSET
        ControlLook.DropDownFooter.Font.Color = clWindowText
        ControlLook.DropDownFooter.Font.Height = -11
        ControlLook.DropDownFooter.Font.Name = 'Tahoma'
        ControlLook.DropDownFooter.Font.Style = []
        ControlLook.DropDownFooter.Buttons = <>
        Filter = <>
        FilterDropDown.Font.Charset = DEFAULT_CHARSET
        FilterDropDown.Font.Color = clWindowText
        FilterDropDown.Font.Height = -11
        FilterDropDown.Font.Name = 'Tahoma'
        FilterDropDown.Font.Style = []
        FixedRowHeight = 26
        FixedFont.Charset = DEFAULT_CHARSET
        FixedFont.Color = clWindowText
        FixedFont.Height = -12
        FixedFont.Name = 'Segoe UI'
        FixedFont.Style = [fsBold]
        FloatFormat = '%.2f'
        Look = glOffice2019White
        PrintSettings.Font.Charset = DEFAULT_CHARSET
        PrintSettings.Font.Color = clWindowText
        PrintSettings.Font.Height = -11
        PrintSettings.Font.Name = 'Tahoma'
        PrintSettings.Font.Style = []
        PrintSettings.FixedFont.Charset = DEFAULT_CHARSET
        PrintSettings.FixedFont.Color = clWindowText
        PrintSettings.FixedFont.Height = -11
        PrintSettings.FixedFont.Name = 'Tahoma'
        PrintSettings.FixedFont.Style = []
        PrintSettings.HeaderFont.Charset = DEFAULT_CHARSET
        PrintSettings.HeaderFont.Color = clWindowText
        PrintSettings.HeaderFont.Height = -11
        PrintSettings.HeaderFont.Name = 'Tahoma'
        PrintSettings.HeaderFont.Style = []
        PrintSettings.FooterFont.Charset = DEFAULT_CHARSET
        PrintSettings.FooterFont.Color = clWindowText
        PrintSettings.FooterFont.Height = -11
        PrintSettings.FooterFont.Name = 'Tahoma'
        PrintSettings.FooterFont.Style = []
        SearchFooter.Font.Charset = DEFAULT_CHARSET
        SearchFooter.Font.Color = clWindowText
        SearchFooter.Font.Height = -11
        SearchFooter.Font.Name = 'Tahoma'
        SearchFooter.Font.Style = []
        ShowDesignHelper = False
        Version = '2.6.0.0'
        AutoCreateColumns = True
        AutoRemoveColumns = True
        Columns = <>
        DataSetType = dtNonSequenced
        DataSource = DSOperatore
        ShowUnicode = True
        PageMode = False
      end
    end
    object pgPagamento: TAdvOfficePage
      Left = 1
      Top = 26
      Width = 898
      Height = 419
      Caption = 'Per pagamento'
      object GridPagamento: TDBAdvGrid
        Left = 0
        Top = 0
        Width = 898
        Height = 419
        Align = alClient
        ColCount = 5
        FixedCols = 0
        RowCount = 2
        Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRangeSelect, goRowSelect]
        ScrollBars = ssBoth
        TabOrder = 0
        GridLineColor = 15790320
        GridFixedLineColor = 13421772
        ActiveCellFont.Charset = DEFAULT_CHARSET
        ActiveCellFont.Color = clWindowText
        ActiveCellFont.Height = -12
        ActiveCellFont.Name = 'Segoe UI'
        ActiveCellFont.Style = [fsBold]
        ControlLook.DropDownHeader.Font.Charset = DEFAULT_CHARSET
        ControlLook.DropDownHeader.Font.Color = clWindowText
        ControlLook.DropDownHeader.Font.Height = -11
        ControlLook.DropDownHeader.Font.Name = 'Tahoma'
        ControlLook.DropDownHeader.Font.Style = []
        ControlLook.DropDownHeader.Buttons = <>
        ControlLook.DropDownFooter.Font.Charset = DEFAULT_CHARSET
        ControlLook.DropDownFooter.Font.Color = clWindowText
        ControlLook.DropDownFooter.Font.Height = -11
        ControlLook.DropDownFooter.Font.Name = 'Tahoma'
        ControlLook.DropDownFooter.Font.Style = []
        ControlLook.DropDownFooter.Buttons = <>
        Filter = <>
        FilterDropDown.Font.Charset = DEFAULT_CHARSET
        FilterDropDown.Font.Color = clWindowText
        FilterDropDown.Font.Height = -11
        FilterDropDown.Font.Name = 'Tahoma'
        FilterDropDown.Font.Style = []
        FixedRowHeight = 26
        FixedFont.Charset = DEFAULT_CHARSET
        FixedFont.Color = clWindowText
        FixedFont.Height = -12
        FixedFont.Name = 'Segoe UI'
        FixedFont.Style = [fsBold]
        FloatFormat = '%.2f'
        Look = glOffice2019White
        PrintSettings.Font.Charset = DEFAULT_CHARSET
        PrintSettings.Font.Color = clWindowText
        PrintSettings.Font.Height = -11
        PrintSettings.Font.Name = 'Tahoma'
        PrintSettings.Font.Style = []
        PrintSettings.FixedFont.Charset = DEFAULT_CHARSET
        PrintSettings.FixedFont.Color = clWindowText
        PrintSettings.FixedFont.Height = -11
        PrintSettings.FixedFont.Name = 'Tahoma'
        PrintSettings.FixedFont.Style = []
        PrintSettings.HeaderFont.Charset = DEFAULT_CHARSET
        PrintSettings.HeaderFont.Color = clWindowText
        PrintSettings.HeaderFont.Height = -11
        PrintSettings.HeaderFont.Name = 'Tahoma'
        PrintSettings.HeaderFont.Style = []
        PrintSettings.FooterFont.Charset = DEFAULT_CHARSET
        PrintSettings.FooterFont.Color = clWindowText
        PrintSettings.FooterFont.Height = -11
        PrintSettings.FooterFont.Name = 'Tahoma'
        PrintSettings.FooterFont.Style = []
        SearchFooter.Font.Charset = DEFAULT_CHARSET
        SearchFooter.Font.Color = clWindowText
        SearchFooter.Font.Height = -11
        SearchFooter.Font.Name = 'Tahoma'
        SearchFooter.Font.Style = []
        ShowDesignHelper = False
        Version = '2.6.0.0'
        AutoCreateColumns = True
        AutoRemoveColumns = True
        Columns = <>
        DataSetType = dtNonSequenced
        DataSource = DSPagamento
        ShowUnicode = True
        PageMode = False
      end
    end
    object pgServizi: TAdvOfficePage
      Left = 1
      Top = 26
      Width = 898
      Height = 419
      Caption = 'Servizi / prodotti'
      object GridServizi: TDBAdvGrid
        Left = 0
        Top = 0
        Width = 898
        Height = 419
        Align = alClient
        ColCount = 5
        FixedCols = 0
        RowCount = 2
        Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goRangeSelect, goRowSelect]
        ScrollBars = ssBoth
        TabOrder = 0
        GridLineColor = 15790320
        GridFixedLineColor = 13421772
        ActiveCellFont.Charset = DEFAULT_CHARSET
        ActiveCellFont.Color = clWindowText
        ActiveCellFont.Height = -12
        ActiveCellFont.Name = 'Segoe UI'
        ActiveCellFont.Style = [fsBold]
        ControlLook.DropDownHeader.Font.Charset = DEFAULT_CHARSET
        ControlLook.DropDownHeader.Font.Color = clWindowText
        ControlLook.DropDownHeader.Font.Height = -11
        ControlLook.DropDownHeader.Font.Name = 'Tahoma'
        ControlLook.DropDownHeader.Font.Style = []
        ControlLook.DropDownHeader.Buttons = <>
        ControlLook.DropDownFooter.Font.Charset = DEFAULT_CHARSET
        ControlLook.DropDownFooter.Font.Color = clWindowText
        ControlLook.DropDownFooter.Font.Height = -11
        ControlLook.DropDownFooter.Font.Name = 'Tahoma'
        ControlLook.DropDownFooter.Font.Style = []
        ControlLook.DropDownFooter.Buttons = <>
        Filter = <>
        FilterDropDown.Font.Charset = DEFAULT_CHARSET
        FilterDropDown.Font.Color = clWindowText
        FilterDropDown.Font.Height = -11
        FilterDropDown.Font.Name = 'Tahoma'
        FilterDropDown.Font.Style = []
        FixedRowHeight = 26
        FixedFont.Charset = DEFAULT_CHARSET
        FixedFont.Color = clWindowText
        FixedFont.Height = -12
        FixedFont.Name = 'Segoe UI'
        FixedFont.Style = [fsBold]
        FloatFormat = '%.2f'
        Look = glOffice2019White
        PrintSettings.Font.Charset = DEFAULT_CHARSET
        PrintSettings.Font.Color = clWindowText
        PrintSettings.Font.Height = -11
        PrintSettings.Font.Name = 'Tahoma'
        PrintSettings.Font.Style = []
        PrintSettings.FixedFont.Charset = DEFAULT_CHARSET
        PrintSettings.FixedFont.Color = clWindowText
        PrintSettings.FixedFont.Height = -11
        PrintSettings.FixedFont.Name = 'Tahoma'
        PrintSettings.FixedFont.Style = []
        PrintSettings.HeaderFont.Charset = DEFAULT_CHARSET
        PrintSettings.HeaderFont.Color = clWindowText
        PrintSettings.HeaderFont.Height = -11
        PrintSettings.HeaderFont.Name = 'Tahoma'
        PrintSettings.HeaderFont.Style = []
        PrintSettings.FooterFont.Charset = DEFAULT_CHARSET
        PrintSettings.FooterFont.Color = clWindowText
        PrintSettings.FooterFont.Height = -11
        PrintSettings.FooterFont.Name = 'Tahoma'
        PrintSettings.FooterFont.Style = []
        SearchFooter.Font.Charset = DEFAULT_CHARSET
        SearchFooter.Font.Color = clWindowText
        SearchFooter.Font.Height = -11
        SearchFooter.Font.Name = 'Tahoma'
        SearchFooter.Font.Style = []
        ShowDesignHelper = False
        Version = '2.6.0.0'
        AutoCreateColumns = True
        AutoRemoveColumns = True
        Columns = <>
        DataSetType = dtNonSequenced
        DataSource = DSServizi
        ShowUnicode = True
        PageMode = False
      end
    end
  end
  object pnlBottom: TAdvPanel
    Left = 0
    Top = 536
    Width = 900
    Height = 24
    Align = alBottom
    UseDockManager = True
    Version = '2.8.0.0'
    Caption.Visible = False
    object lblTotale: TLabel
      Left = 8
      Top = 4
      Width = 100
      Height = 15
      Caption = 'Incasso periodo'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Segoe UI'
      Font.Style = [fsBold]
      ParentFont = False
    end
  end
  object QGiorno: TFDQuery
    Left = 40
    Top = 480
  end
  object DSGiorno: TDataSource
    DataSet = QGiorno
    Left = 40
    Top = 520
  end
  object QOperatore: TFDQuery
    Left = 100
    Top = 480
  end
  object DSOperatore: TDataSource
    DataSet = QOperatore
    Left = 100
    Top = 520
  end
  object QPagamento: TFDQuery
    Left = 160
    Top = 480
  end
  object DSPagamento: TDataSource
    DataSet = QPagamento
    Left = 160
    Top = 520
  end
  object QServizi: TFDQuery
    Left = 220
    Top = 480
  end
  object DSServizi: TDataSource
    DataSet = QServizi
    Left = 220
    Top = 520
  end
end
