object frmZonaEdit: TfrmZonaEdit
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  BorderStyle = bsDialog
  Caption = 'Zona'
  ClientHeight = 240
  ClientWidth = 420
  Color = clWhite
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Comfortaa'
  Font.Style = []
  OldCreateOrder = False
  Position = poMainFormCenter
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 16
  object lblCodice: TLabel
    Left = 24
    Top = 24
    Width = 44
    Height = 16
    Caption = 'Codice'
  end
  object lblDescrizione: TLabel
    Left = 24
    Top = 76
    Width = 74
    Height = 16
    Caption = 'Descrizione'
  end
  object lblSuperficie: TLabel
    Left = 24
    Top = 128
    Width = 90
    Height = 16
    Caption = 'Superficie (mq)'
  end
  object edtCodice: TAdvEdit
    Left = 24
    Top = 44
    Width = 180
    Height = 26
    EmptyTextStyle = []
    MaxLength = 20
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Comfortaa'
    Font.Style = []
    ParentFont = False
    TabOrder = 0
    Version = '3.5.0.0'
    Visible = True
  end
  object edtDescrizione: TAdvEdit
    Left = 24
    Top = 96
    Width = 372
    Height = 26
    EmptyTextStyle = []
    MaxLength = 200
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Comfortaa'
    Font.Style = []
    ParentFont = False
    TabOrder = 1
    Version = '3.5.0.0'
    Visible = True
  end
  object edtSuperficie: TAdvEdit
    Left = 24
    Top = 148
    Width = 120
    Height = 26
    EditType = etFloat
    EmptyTextStyle = []
    Color = clWhite
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Comfortaa'
    Font.Style = []
    ParentFont = False
    TabOrder = 2
    Text = '0'
    Version = '3.5.0.0'
    Visible = True
  end
  object chkAttiva: TCheckBox
    Left = 180
    Top = 151
    Width = 100
    Height = 20
    Caption = 'Attiva'
    Checked = True
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Comfortaa'
    Font.Style = []
    ParentFont = False
    State = cbChecked
    TabOrder = 3
  end
  object pnlBottoni: TAdvPanel
    Left = 0
    Top = 191
    Width = 420
    Height = 49
    Align = alBottom
    ParentColor = False
    TabOrder = 4
    Version = '2.4.0.0'
    BorderColor = clNone
    Caption.Text = ''
    Caption.Visible = False
    Fill.Color = clWhite
    Fill.ColorTo = clWhite
    Fill.BorderColor = clSilver
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Comfortaa'
    Font.Style = []
    ParentFont = False
    object btnOk: TAdvGlowButton
      Left = 208
      Top = 9
      Width = 100
      Height = 32
      Caption = 'Salva'
      Default = True
      TabOrder = 0
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      Version = '1.7.0.0'
      OnClick = btnOkClick
    end
    object btnAnnulla: TAdvGlowButton
      Left = 316
      Top = 9
      Width = 100
      Height = 32
      Cancel = True
      Caption = 'Annulla'
      ModalResult = 2
      TabOrder = 1
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Comfortaa'
      Font.Style = []
      ParentFont = False
      Version = '1.7.0.0'
    end
  end
  object styZonaEdit: TAdvFormStyler
    Style = tsWindows8
    Left = 344
    Top = 24
  end
end
